AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

# RSpec Cop Exclusions

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/*
